In [9]:
def fn_area(shape,**kwargs):
    if shape == 'square':
        area =  kwargs['side'] ** 2
    elif shape=='rectangle':
        area = kwargs['length'] * kwargs['breadth']
    elif shape =='circle':
        area = 3.14 * kwargs['radius'] **2
    return area

    

In [15]:
fn_area('square',side=10)

100

In [17]:
import numpy as np

In [18]:
numpy provides one DS ; ndarray

N-Dimensional
Homogeneous structure
Broadcasting(no loop)

1.How to create; from default python ds, inbuilt methods, 
2.how to access the elements
3.updation
methods and attributes
maths operations and indexing

SyntaxError: invalid syntax (<ipython-input-18-b1a8317e7f7f>, line 1)

In [19]:
l1 = [1,2,3,4,5]

In [20]:
type(l1)

list

In [21]:
a1

NameError: name 'a1' is not defined

In [22]:
type(a1)

NameError: name 'a1' is not defined

In [25]:
a2=np.array(range(10))

In [26]:
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
### attributes for array inspection
size,shape,dimension,byte

In [28]:
a2.ndim

1

In [29]:
a2.size

10

In [31]:
a2.shape

(10,)

In [32]:
a2.nbytes

40

In [34]:
a2.dtype

dtype('int32')

In [35]:
a3=np.array([1,2,3,4,5])

In [36]:
a3.shape

(5,)

In [39]:
a3=np.array([[1,2,3,4,5],[1,2,3,4,5]])

In [40]:
a3.shape

(2, 5)

In [41]:
a3

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [47]:
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
a4=np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])

In [49]:
a4

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [50]:
a3[::,2]

array([3, 3])

In [51]:
### questions
1.import the package numpy as np
2.create 1d array "a1" from the list and display the properties
3.create 2d array "a2" with shape (4,5) and display the properties
4.get only first row from a2
5.get only last column from a2
6.get the value at position 2,4
7.get the data from first two rows and last  three columns


SyntaxError: invalid syntax (<ipython-input-51-7527c18a6ef0>, line 2)

In [52]:
import numpy as p

In [53]:
a1=[1,2,3,4,5]

In [54]:
type(a1)

list

In [61]:
a2=np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])

In [62]:
a2.shape

(4, 5)

In [65]:
a2[0]

array([1, 2, 3, 4, 5])

In [71]:
a2[::,::]

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [73]:
a2[::,4]

array([5, 5, 5, 5])

In [76]:
a2[2,4]

5

In [88]:
a2[0:2,2::]

array([[3, 4, 5],
       [3, 4, 5]])

In [89]:
a2

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [90]:
a2+100

array([[101, 102, 103, 104, 105],
       [101, 102, 103, 104, 105],
       [101, 102, 103, 104, 105],
       [101, 102, 103, 104, 105]])

In [91]:
a2.mean()

3.0

In [93]:
a2>a2.mean()

array([[False, False, False,  True,  True],
       [False, False, False,  True,  True],
       [False, False, False,  True,  True],
       [False, False, False,  True,  True]])

In [94]:
a2[a2>a2.mean()]

array([4, 5, 4, 5, 4, 5, 4, 5])